
services:
  payment:
    profiles:
      - prod
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    depends_on:
      - db
      - redis
      - kafka

  payment-dev:
    profiles:
      - dev
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.dev
    ports:
      - "8080:8080"
    env_file:
      - ../../.env
    volumes:
      - ../..:/app
    depends_on:
      - db
      # - redis
      # - kafka

  db:
    image: postgres:15
    restart: always
    env_file:
      - ../../.env
    # environment:
    #   - POSTGRES_DB
    #   - POSTGRES_USER
    #   - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5



  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - "6379:6379"  # Remove or restrict in production
    volumes:
      - ../../redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf
      - redis_data:/bitnami/redis/data
    env_file:
      - ../../.env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5


  # zookeeper:
  #   image: bitnami/zookeeper:latest
  #   ports:
  #     - "2181:2181"

  kafka:
    image: bitnami/kafka:latest
  
    env_file:
      - ../../.env
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

volumes:
  pgdata:
  redis_data:
