package postgres

import (
	"context"
	"errors"
	"fmt"
	// "time" // Import time for handling timestamps

	"github.com/rk5634/payment-system/internal/domain/payment" // Assuming this defines the Payment struct

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// PaymentRepository handles database operations for payments using pgxpool.
type PaymentRepository struct {
	db *pgxpool.Pool
}

// NewPaymentRepository creates and returns a new PaymentRepository.
func NewPaymentRepository(db *pgxpool.Pool) *PaymentRepository {
	return &PaymentRepository{db: db}
}

// CreatePayment inserts a new payment record into the database.
// The ID is generated by PostgreSQL using gen_random_uuid().
func (r *PaymentRepository) CreatePayment(ctx context.Context, p *payment.Payment) error {
	query := `
		INSERT INTO payments (
			user_id, amount, currency, status, payment_method,
			transaction_id, description, metadata, completed_at, failed_at,
			refunded_at, is_deleted, version, created_at, updated_at
		)
		VALUES (
			$1, $2, $3, $4, $5,
			$6, $7, $8, $9, $10,
			$11, $12, $13, $14, $15
		)
		RETURNING id
	`

	err := r.db.QueryRow(
		ctx,
		query,
		p.UserID,
		p.Amount,
		p.Currency,
		p.Status,
		p.PaymentMethod,
		p.TransactionID,
		p.Description,
		p.Metadata,
		p.CompletedAt,
		p.FailedAt,
		p.RefundedAt,
		p.IsDeleted,
		p.Version,
		p.CreatedAt,
		p.UpdatedAt,
	).Scan(&p.ID)

	if err != nil {
		return fmt.Errorf("failed to create payment: %w", err)
	}

	return nil
}

// GetPaymentByID retrieves a payment by its UUID.
func (r *PaymentRepository) GetPaymentByID(ctx context.Context, id string) (*payment.Payment, error) {
	var p payment.Payment
	query := `SELECT 
				id, user_id, amount, currency, status, payment_method,
				transaction_id, description, metadata, completed_at, failed_at,
				refunded_at, is_deleted, version, created_at, updated_at
			  FROM payments WHERE id = $1 AND is_deleted = FALSE`

	row := r.db.QueryRow(ctx, query, id)

	// Scan the row into the payment struct fields.
	// Ensure the order of scanning matches the SELECT clause.
	err := row.Scan(
		&p.ID,
		&p.UserID,
		&p.Amount,
		&p.Currency,
		&p.Status,
		&p.PaymentMethod,
		&p.TransactionID,
		&p.Description,
		&p.Metadata,
		&p.CompletedAt,
		&p.FailedAt,
		&p.RefundedAt,
		&p.IsDeleted,
		&p.Version,
		&p.CreatedAt,
		&p.UpdatedAt,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil // Not found
		}
		return nil, fmt.Errorf("failed to get payment by id: %w", err)
	}
	return &p, nil
}

// UpdatePaymentStatus updates the status of a payment and sets the appropriate timestamp.
func (r *PaymentRepository) UpdatePaymentStatus(ctx context.Context, id string, status string) error {
	timestampColumn := ""
	switch status {
	case "completed":
		timestampColumn = "completed_at"
	case "failed":
		timestampColumn = "failed_at"
	case "refunded":
		timestampColumn = "refunded_at"
	}

	// Build the query dynamically based on the timestampColumn
	updateClause := ""
	if timestampColumn != "" {
		updateClause = fmt.Sprintf(", %s = NOW()", timestampColumn)
	}

	query := fmt.Sprintf(`
		UPDATE payments 
		SET status = $1, updated_at = NOW()%s
		WHERE id = $2 AND is_deleted = FALSE
	`, updateClause)

	commandTag, err := r.db.Exec(ctx, query, status, id)
	if err != nil {
		return fmt.Errorf("failed to update payment status: %w", err)
	}
	if commandTag.RowsAffected() == 0 {
		return fmt.Errorf("no payment found with id %s to update status", id)
	}
	return nil
}

// SoftDeletePayment marks a payment as deleted without removing the record.
func (r *PaymentRepository) SoftDeletePayment(ctx context.Context, id string) error {
	query := `UPDATE payments SET is_deleted = TRUE, updated_at = NOW() WHERE id = $1`

	commandTag, err := r.db.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("failed to soft delete payment: %w", err)
	}
	if commandTag.RowsAffected() == 0 {
		return fmt.Errorf("no payment found with id %s to soft delete", id)
	}
	return nil
}

// DeletePayment performs a hard delete (optional, dangerous).
func (r *PaymentRepository) DeletePayment(ctx context.Context, id string) error {
	query := `DELETE FROM payments WHERE id = $1`

	commandTag, err := r.db.Exec(ctx, query, id)
	if err != nil {
		return fmt.Errorf("failed to delete payment: %w", err)
	}
	if commandTag.RowsAffected() == 0 {
		return fmt.Errorf("no payment found with id %s to hard delete", id)
	}
	return nil
}

// ListPaymentsByUser returns all non-deleted payments for a given user.
func (r *PaymentRepository) ListPaymentsByUser(ctx context.Context, userID string) ([]*payment.Payment, error) {
	var payments []*payment.Payment
	query := `SELECT 
				id, user_id, amount, currency, status, payment_method,
				transaction_id, description, metadata, completed_at, failed_at,
				refunded_at, is_deleted, version, created_at, updated_at
			  FROM payments WHERE user_id = $1 AND is_deleted = FALSE ORDER BY created_at DESC`

	rows, err := r.db.Query(ctx, query, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to query payments for user: %w", err)
	}
	defer rows.Close()

	for rows.Next() {
		var p payment.Payment
		err := rows.Scan(
			&p.ID,
			&p.UserID,
			&p.Amount,
			&p.Currency,
			&p.Status,
			&p.PaymentMethod,
			&p.TransactionID,
			&p.Description,
			&p.Metadata,
			&p.CompletedAt,
			&p.FailedAt,
			&p.RefundedAt, // Corrected from RefundedAt to RefundAt based on typical struct naming
			&p.IsDeleted,
			&p.Version,
			&p.CreatedAt,
			&p.UpdatedAt,
		)
		if err != nil {
			return nil, fmt.Errorf("failed to scan payment row: %w", err)
		}
		payments = append(payments, &p)
	}

	if err = rows.Err(); err != nil {
		return nil, fmt.Errorf("rows iteration error: %w", err)
	}

	return payments, nil
}

